
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('@prisma/client/runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.0
 * Query Engine version: 2ba551f319ab1df4bc874a89965d8b3641056773
 */
Prisma.prismaVersion = {
  client: "6.19.0",
  engine: "2ba551f319ab1df4bc874a89965d8b3641056773"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.CenterScalarFieldEnum = {
  id: 'id',
  name: 'name',
  shortName: 'shortName',
  addressLine: 'addressLine',
  locality: 'locality',
  city: 'city',
  state: 'state',
  postalCode: 'postalCode',
  latitude: 'latitude',
  longitude: 'longitude',
  googleMapsUrl: 'googleMapsUrl',
  isActive: 'isActive',
  displayOrder: 'displayOrder',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  location: 'location',
  address: 'address'
};

exports.Prisma.CoachScalarFieldEnum = {
  id: 'id',
  fullName: 'fullName',
  email: 'email',
  passwordHash: 'passwordHash',
  role: 'role',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CoachCenterScalarFieldEnum = {
  id: 'id',
  coachId: 'coachId',
  centerId: 'centerId'
};

exports.Prisma.StudentScalarFieldEnum = {
  id: 'id',
  fullName: 'fullName',
  dateOfBirth: 'dateOfBirth',
  phoneNumber: 'phoneNumber',
  parentName: 'parentName',
  parentPhoneNumber: 'parentPhoneNumber',
  email: 'email',
  passwordHash: 'passwordHash',
  centerId: 'centerId',
  joiningDate: 'joiningDate',
  programType: 'programType',
  monthlyFeeAmount: 'monthlyFeeAmount',
  paymentFrequency: 'paymentFrequency',
  walletBalance: 'walletBalance',
  lastFeeDeduction: 'lastFeeDeduction',
  status: 'status',
  churnedDate: 'churnedDate',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PaymentScalarFieldEnum = {
  id: 'id',
  studentId: 'studentId',
  centerId: 'centerId',
  amount: 'amount',
  paymentDate: 'paymentDate',
  paymentMode: 'paymentMode',
  upiOrTxnReference: 'upiOrTxnReference',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.FanUserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  passwordHash: 'passwordHash',
  role: 'role',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.FanProfileScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  fullName: 'fullName',
  phone: 'phone',
  city: 'city',
  centerPreference: 'centerPreference',
  tierId: 'tierId',
  points: 'points',
  badges: 'badges',
  streakDays: 'streakDays',
  joinedAt: 'joinedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.FanTierScalarFieldEnum = {
  id: 'id',
  name: 'name',
  monthlyPriceINR: 'monthlyPriceINR',
  yearlyPriceINR: 'yearlyPriceINR',
  benefitsJson: 'benefitsJson',
  featureFlags: 'featureFlags',
  sortOrder: 'sortOrder',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.FanSponsorScalarFieldEnum = {
  id: 'id',
  name: 'name',
  logoAssetKey: 'logoAssetKey',
  brandPrimary: 'brandPrimary',
  brandSecondary: 'brandSecondary',
  description: 'description',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.RewardCampaignScalarFieldEnum = {
  id: 'id',
  sponsorId: 'sponsorId',
  title: 'title',
  type: 'type',
  copy: 'copy',
  rulesJson: 'rulesJson',
  validFrom: 'validFrom',
  validTo: 'validTo',
  tierEligibility: 'tierEligibility',
  isActive: 'isActive',
  priority: 'priority',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CouponPoolScalarFieldEnum = {
  id: 'id',
  sponsorId: 'sponsorId',
  name: 'name',
  codeType: 'codeType',
  multiUseCode: 'multiUseCode',
  discountType: 'discountType',
  discountValue: 'discountValue',
  conditionsText: 'conditionsText',
  tierEligibility: 'tierEligibility',
  maxRedemptions: 'maxRedemptions',
  expiresAt: 'expiresAt',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CouponCodeScalarFieldEnum = {
  id: 'id',
  couponPoolId: 'couponPoolId',
  code: 'code',
  isUsed: 'isUsed',
  usedAt: 'usedAt',
  createdAt: 'createdAt'
};

exports.Prisma.CouponRedemptionScalarFieldEnum = {
  id: 'id',
  fanId: 'fanId',
  couponPoolId: 'couponPoolId',
  codeUsed: 'codeUsed',
  redeemedAt: 'redeemedAt',
  status: 'status'
};

exports.Prisma.FanQuestScalarFieldEnum = {
  id: 'id',
  title: 'title',
  description: 'description',
  pointsReward: 'pointsReward',
  badgeReward: 'badgeReward',
  unlockRule: 'unlockRule',
  tierEligibility: 'tierEligibility',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.FanGameSessionScalarFieldEnum = {
  id: 'id',
  fanId: 'fanId',
  gameType: 'gameType',
  input: 'input',
  result: 'result',
  pointsEarned: 'pointsEarned',
  createdAt: 'createdAt'
};

exports.Prisma.FanConversionLeadScalarFieldEnum = {
  id: 'id',
  fanId: 'fanId',
  programInterest: 'programInterest',
  status: 'status',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.FanOnboardingScalarFieldEnum = {
  id: 'id',
  fanId: 'fanId',
  persona: 'persona',
  favoritePlayer: 'favoritePlayer',
  locality: 'locality',
  goals: 'goals',
  assignedTierId: 'assignedTierId',
  completedAt: 'completedAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.FanPointLedgerScalarFieldEnum = {
  id: 'id',
  fanId: 'fanId',
  delta: 'delta',
  reason: 'reason',
  source: 'source',
  actorId: 'actorId',
  createdAt: 'createdAt'
};

exports.Prisma.FanBadgeEarnedScalarFieldEnum = {
  id: 'id',
  fanId: 'fanId',
  badgeKey: 'badgeKey',
  badgeName: 'badgeName',
  source: 'source',
  earnedAt: 'earnedAt'
};

exports.Prisma.MatchdayMomentScalarFieldEnum = {
  id: 'id',
  title: 'title',
  category: 'category',
  mediaUrl: 'mediaUrl',
  thumbnailUrl: 'thumbnailUrl',
  fixtureId: 'fixtureId',
  isFeatured: 'isFeatured',
  isLocked: 'isLocked',
  unlockAt: 'unlockAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.DynamicRewardRuleScalarFieldEnum = {
  id: 'id',
  key: 'key',
  title: 'title',
  description: 'description',
  rulesJson: 'rulesJson',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AuditLogScalarFieldEnum = {
  id: 'id',
  actorAdminId: 'actorAdminId',
  action: 'action',
  entityType: 'entityType',
  entityId: 'entityId',
  before: 'before',
  after: 'after',
  createdAt: 'createdAt'
};

exports.Prisma.SessionScalarFieldEnum = {
  id: 'id',
  centerId: 'centerId',
  coachId: 'coachId',
  title: 'title',
  description: 'description',
  programmeId: 'programmeId',
  sessionDate: 'sessionDate',
  startTime: 'startTime',
  endTime: 'endTime',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SessionParticipantScalarFieldEnum = {
  id: 'id',
  sessionId: 'sessionId',
  studentId: 'studentId',
  createdAt: 'createdAt'
};

exports.Prisma.AttendanceScalarFieldEnum = {
  id: 'id',
  sessionId: 'sessionId',
  studentId: 'studentId',
  status: 'status',
  notes: 'notes',
  markedBy: 'markedBy',
  markedAt: 'markedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.FixtureScalarFieldEnum = {
  id: 'id',
  centerId: 'centerId',
  coachId: 'coachId',
  matchType: 'matchType',
  opponent: 'opponent',
  matchDate: 'matchDate',
  matchTime: 'matchTime',
  venue: 'venue',
  notes: 'notes',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.FixturePlayerScalarFieldEnum = {
  id: 'id',
  fixtureId: 'fixtureId',
  studentId: 'studentId',
  position: 'position',
  role: 'role',
  selectionStatus: 'selectionStatus',
  selectionReason: 'selectionReason',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ClubEventScalarFieldEnum = {
  id: 'id',
  type: 'type',
  title: 'title',
  startAt: 'startAt',
  endAt: 'endAt',
  allDay: 'allDay',
  venueName: 'venueName',
  venueAddress: 'venueAddress',
  googleMapsUrl: 'googleMapsUrl',
  competition: 'competition',
  opponent: 'opponent',
  homeAway: 'homeAway',
  teamId: 'teamId',
  centerId: 'centerId',
  status: 'status',
  notes: 'notes',
  createdByUserId: 'createdByUserId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ClubEventPlayerScalarFieldEnum = {
  id: 'id',
  eventId: 'eventId',
  studentId: 'studentId',
  position: 'position',
  role: 'role',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.VideoScalarFieldEnum = {
  id: 'id',
  title: 'title',
  description: 'description',
  videoUrl: 'videoUrl',
  platform: 'platform',
  category: 'category',
  thumbnailUrl: 'thumbnailUrl',
  mediaType: 'mediaType',
  fileUrl: 'fileUrl',
  fileSize: 'fileSize',
  fileName: 'fileName',
  mimeType: 'mimeType',
  createdById: 'createdById',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PostScalarFieldEnum = {
  id: 'id',
  title: 'title',
  description: 'description',
  mediaType: 'mediaType',
  mediaUrl: 'mediaUrl',
  platform: 'platform',
  centerId: 'centerId',
  createdByRole: 'createdByRole',
  createdById: 'createdById',
  approvalStatus: 'approvalStatus',
  approvedById: 'approvedById',
  approvedAt: 'approvedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CommentScalarFieldEnum = {
  id: 'id',
  postId: 'postId',
  content: 'content',
  createdByRole: 'createdByRole',
  createdById: 'createdById',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.VoteScalarFieldEnum = {
  id: 'id',
  sessionId: 'sessionId',
  voterRole: 'voterRole',
  voterId: 'voterId',
  votedForId: 'votedForId',
  points: 'points',
  centerId: 'centerId',
  createdAt: 'createdAt'
};

exports.Prisma.StudentStatsScalarFieldEnum = {
  id: 'id',
  studentId: 'studentId',
  centerId: 'centerId',
  totalPoints: 'totalPoints',
  studentVotes: 'studentVotes',
  coachVotes: 'coachVotes',
  sessionsVoted: 'sessionsVoted',
  currentStreak: 'currentStreak',
  longestStreak: 'longestStreak',
  weeklyPoints: 'weeklyPoints',
  monthlyPoints: 'monthlyPoints',
  lastVotedAt: 'lastVotedAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.BadgeScalarFieldEnum = {
  id: 'id',
  studentStatsId: 'studentStatsId',
  badgeType: 'badgeType',
  earnedAt: 'earnedAt'
};

exports.Prisma.WebsiteLeadScalarFieldEnum = {
  id: 'id',
  source: 'source',
  playerName: 'playerName',
  playerDob: 'playerDob',
  ageBracket: 'ageBracket',
  guardianName: 'guardianName',
  phone: 'phone',
  email: 'email',
  preferredCentre: 'preferredCentre',
  programmeInterest: 'programmeInterest',
  playingPosition: 'playingPosition',
  currentLevel: 'currentLevel',
  heardFrom: 'heardFrom',
  notes: 'notes',
  skillsShowcaseLink: 'skillsShowcaseLink',
  status: 'status',
  assignedTo: 'assignedTo',
  internalNotes: 'internalNotes',
  convertedPlayerId: 'convertedPlayerId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.LegacyLeadScalarFieldEnum = {
  id: 'id',
  source: 'source',
  name: 'name',
  phone: 'phone',
  age: 'age',
  heightCmInput: 'heightCmInput',
  weightKgInput: 'weightKgInput',
  heightCmBucket: 'heightCmBucket',
  weightKgBucket: 'weightKgBucket',
  matchedPlayerId: 'matchedPlayerId',
  matchedPlayerName: 'matchedPlayerName',
  matchedPlayerPosition: 'matchedPlayerPosition',
  matchedPlayerArchetype: 'matchedPlayerArchetype',
  matchedPlayerLegacy: 'matchedPlayerLegacy',
  consent: 'consent',
  status: 'status',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CrmUserScalarFieldEnum = {
  id: 'id',
  fullName: 'fullName',
  email: 'email',
  passwordHash: 'passwordHash',
  role: 'role',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CrmSettingsScalarFieldEnum = {
  id: 'id',
  stages: 'stages',
  tags: 'tags',
  slaHoursByStage: 'slaHoursByStage',
  assignmentRules: 'assignmentRules',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CrmLeadScalarFieldEnum = {
  id: 'id',
  sourceType: 'sourceType',
  sourceId: 'sourceId',
  primaryName: 'primaryName',
  phone: 'phone',
  email: 'email',
  city: 'city',
  preferredCentre: 'preferredCentre',
  programmeInterest: 'programmeInterest',
  stage: 'stage',
  status: 'status',
  priority: 'priority',
  score: 'score',
  ownerId: 'ownerId',
  tags: 'tags',
  customFields: 'customFields',
  convertedStudentId: 'convertedStudentId',
  convertedFanId: 'convertedFanId',
  convertedOrderId: 'convertedOrderId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CrmManualLeadSourceScalarFieldEnum = {
  id: 'id',
  primaryName: 'primaryName',
  phone: 'phone',
  email: 'email',
  preferredCentre: 'preferredCentre',
  programmeInterest: 'programmeInterest',
  raw: 'raw',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CrmActivityScalarFieldEnum = {
  id: 'id',
  leadId: 'leadId',
  type: 'type',
  occurredAt: 'occurredAt',
  title: 'title',
  body: 'body',
  metadata: 'metadata',
  createdByCrmUserId: 'createdByCrmUserId'
};

exports.Prisma.CrmTaskScalarFieldEnum = {
  id: 'id',
  leadId: 'leadId',
  title: 'title',
  description: 'description',
  dueAt: 'dueAt',
  status: 'status',
  assignedToCrmUserId: 'assignedToCrmUserId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CrmImportJobScalarFieldEnum = {
  id: 'id',
  source: 'source',
  filename: 'filename',
  status: 'status',
  mapping: 'mapping',
  summary: 'summary',
  createdByCrmUserId: 'createdByCrmUserId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CrmImportRowScalarFieldEnum = {
  id: 'id',
  jobId: 'jobId',
  rowNumber: 'rowNumber',
  raw: 'raw',
  normalized: 'normalized',
  isValid: 'isValid',
  error: 'error',
  dedupeKey: 'dedupeKey',
  resolvedLeadId: 'resolvedLeadId',
  createdAt: 'createdAt'
};

exports.Prisma.SystemActivityLogScalarFieldEnum = {
  id: 'id',
  actorType: 'actorType',
  actorId: 'actorId',
  action: 'action',
  entityType: 'entityType',
  entityId: 'entityId',
  before: 'before',
  after: 'after',
  metadata: 'metadata',
  createdAt: 'createdAt'
};

exports.Prisma.ProductScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  description: 'description',
  images: 'images',
  price: 'price',
  currency: 'currency',
  sizes: 'sizes',
  variants: 'variants',
  stock: 'stock',
  category: 'category',
  tags: 'tags',
  displayOrder: 'displayOrder',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.OrderScalarFieldEnum = {
  id: 'id',
  orderNumber: 'orderNumber',
  subtotal: 'subtotal',
  shippingFee: 'shippingFee',
  total: 'total',
  customerName: 'customerName',
  phone: 'phone',
  email: 'email',
  shippingAddress: 'shippingAddress',
  status: 'status',
  paymentProvider: 'paymentProvider',
  paymentReference: 'paymentReference',
  paymentData: 'paymentData',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.OrderItemScalarFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  productId: 'productId',
  productName: 'productName',
  variant: 'variant',
  size: 'size',
  quantity: 'quantity',
  unitPrice: 'unitPrice',
  totalPrice: 'totalPrice'
};

exports.Prisma.CheckoutLeadScalarFieldEnum = {
  id: 'id',
  source: 'source',
  customerName: 'customerName',
  phone: 'phone',
  email: 'email',
  shippingAddress: 'shippingAddress',
  items: 'items',
  subtotal: 'subtotal',
  shippingFee: 'shippingFee',
  total: 'total',
  errorMessage: 'errorMessage',
  status: 'status',
  assignedTo: 'assignedTo',
  internalNotes: 'internalNotes',
  convertedOrderId: 'convertedOrderId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TimelineEventScalarFieldEnum = {
  id: 'id',
  studentId: 'studentId',
  eventType: 'eventType',
  title: 'title',
  description: 'description',
  eventDate: 'eventDate',
  metadata: 'metadata',
  createdByRole: 'createdByRole',
  createdById: 'createdById',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.MonthlyFeedbackScalarFieldEnum = {
  id: 'id',
  studentId: 'studentId',
  coachId: 'coachId',
  month: 'month',
  year: 'year',
  strengths: 'strengths',
  areasToImprove: 'areasToImprove',
  focusGoal: 'focusGoal',
  overallNote: 'overallNote',
  isPublished: 'isPublished',
  publishedById: 'publishedById',
  publishedAt: 'publishedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.WellnessCheckScalarFieldEnum = {
  id: 'id',
  studentId: 'studentId',
  sessionId: 'sessionId',
  checkDate: 'checkDate',
  exertionLevel: 'exertionLevel',
  muscleSoreness: 'muscleSoreness',
  energyLevel: 'energyLevel',
  comment: 'comment',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ProgressRoadmapScalarFieldEnum = {
  id: 'id',
  studentId: 'studentId',
  currentLevel: 'currentLevel',
  nextPotentialLevel: 'nextPotentialLevel',
  attendanceRequirement: 'attendanceRequirement',
  physicalBenchmark: 'physicalBenchmark',
  tacticalRequirement: 'tacticalRequirement',
  coachRecommendation: 'coachRecommendation',
  isEligible: 'isEligible',
  eligibilityNotes: 'eligibilityNotes',
  updatedByRole: 'updatedByRole',
  updatedById: 'updatedById',
  updatedAt: 'updatedAt',
  createdAt: 'createdAt'
};

exports.Prisma.CentreMonthlyMetricsScalarFieldEnum = {
  id: 'id',
  centreId: 'centreId',
  year: 'year',
  month: 'month',
  totalPlayers: 'totalPlayers',
  activePlayers: 'activePlayers',
  churnedPlayers: 'churnedPlayers',
  residential: 'residential',
  nonResidential: 'nonResidential',
  totalRevenue: 'totalRevenue',
  additionalRevenue: 'additionalRevenue',
  netRentalCharges: 'netRentalCharges',
  coachingCosts: 'coachingCosts',
  otherExpenses: 'otherExpenses',
  netProfit: 'netProfit',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PlayerMetricDefinitionScalarFieldEnum = {
  id: 'id',
  key: 'key',
  displayName: 'displayName',
  category: 'category',
  description: 'description',
  minValue: 'minValue',
  maxValue: 'maxValue',
  isActive: 'isActive',
  isCoachOnly: 'isCoachOnly',
  displayOrder: 'displayOrder',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PlayerMetricSnapshotScalarFieldEnum = {
  id: 'id',
  studentId: 'studentId',
  createdByUserId: 'createdByUserId',
  createdByRole: 'createdByRole',
  createdAt: 'createdAt',
  sourceContext: 'sourceContext',
  seasonId: 'seasonId',
  notes: 'notes'
};

exports.Prisma.PlayerMetricValueScalarFieldEnum = {
  id: 'id',
  snapshotId: 'snapshotId',
  metricDefinitionId: 'metricDefinitionId',
  valueNumber: 'valueNumber',
  confidence: 'confidence',
  comment: 'comment'
};

exports.Prisma.PlayerPositionalSuitabilityScalarFieldEnum = {
  id: 'id',
  snapshotId: 'snapshotId',
  position: 'position',
  suitability: 'suitability',
  comment: 'comment'
};

exports.Prisma.PlayerTraitSnapshotScalarFieldEnum = {
  id: 'id',
  snapshotId: 'snapshotId',
  metricDefinitionId: 'metricDefinitionId',
  valueNumber: 'valueNumber',
  comment: 'comment'
};

exports.Prisma.PlayerMetricAuditLogScalarFieldEnum = {
  id: 'id',
  studentId: 'studentId',
  snapshotId: 'snapshotId',
  previousSnapshotId: 'previousSnapshotId',
  changedByUserId: 'changedByUserId',
  changedByRole: 'changedByRole',
  createdAt: 'createdAt',
  diffJson: 'diffJson',
  summary: 'summary'
};

exports.Prisma.PlayerCoachNoteScalarFieldEnum = {
  id: 'id',
  studentId: 'studentId',
  authorUserId: 'authorUserId',
  authorRole: 'authorRole',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  title: 'title',
  body: 'body',
  tags: 'tags',
  relatedSnapshotId: 'relatedSnapshotId',
  isVisibleToPlayer: 'isVisibleToPlayer'
};

exports.Prisma.PlayerReadinessIndexScalarFieldEnum = {
  id: 'id',
  snapshotId: 'snapshotId',
  overall: 'overall',
  technical: 'technical',
  physical: 'physical',
  mental: 'mental',
  attitude: 'attitude',
  tacticalFit: 'tacticalFit',
  explanationJson: 'explanationJson',
  computedAt: 'computedAt'
};

exports.Prisma.ScoutingBoardScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  type: 'type',
  centerId: 'centerId',
  createdByUserId: 'createdByUserId',
  createdByRole: 'createdByRole',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ScoutingBoardPlayerScalarFieldEnum = {
  id: 'id',
  boardId: 'boardId',
  studentId: 'studentId',
  addedAt: 'addedAt',
  addedByUserId: 'addedByUserId',
  addedByRole: 'addedByRole',
  notes: 'notes'
};

exports.Prisma.ScoutingDecisionLogScalarFieldEnum = {
  id: 'id',
  boardId: 'boardId',
  studentId: 'studentId',
  decisionState: 'decisionState',
  notes: 'notes',
  decidedByUserId: 'decidedByUserId',
  decidedByRole: 'decidedByRole',
  decidedAt: 'decidedAt'
};

exports.Prisma.ParentDevelopmentReportScalarFieldEnum = {
  id: 'id',
  studentId: 'studentId',
  snapshotId: 'snapshotId',
  publishedAt: 'publishedAt',
  publishedByUserId: 'publishedByUserId',
  publishedByRole: 'publishedByRole',
  visibleToParent: 'visibleToParent',
  reportingPeriodStart: 'reportingPeriodStart',
  reportingPeriodEnd: 'reportingPeriodEnd',
  contentJson: 'contentJson',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SeasonPlanScalarFieldEnum = {
  id: 'id',
  centerId: 'centerId',
  name: 'name',
  seasonStart: 'seasonStart',
  seasonEnd: 'seasonEnd',
  description: 'description',
  createdByUserId: 'createdByUserId',
  createdByRole: 'createdByRole',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SeasonPhaseScalarFieldEnum = {
  id: 'id',
  seasonPlanId: 'seasonPlanId',
  name: 'name',
  phaseType: 'phaseType',
  startDate: 'startDate',
  endDate: 'endDate',
  description: 'description',
  targetLoadRange: 'targetLoadRange',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TrainingSessionLoadScalarFieldEnum = {
  id: 'id',
  sessionId: 'sessionId',
  seasonPlanId: 'seasonPlanId',
  intensity: 'intensity',
  duration: 'duration',
  focusTags: 'focusTags',
  estimatedLoad: 'estimatedLoad',
  notes: 'notes',
  createdByUserId: 'createdByUserId',
  createdByRole: 'createdByRole',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PlayerWeeklyLoadScalarFieldEnum = {
  id: 'id',
  studentId: 'studentId',
  centerId: 'centerId',
  weekStart: 'weekStart',
  weekEnd: 'weekEnd',
  totalLoad: 'totalLoad',
  sessionCount: 'sessionCount',
  averageIntensity: 'averageIntensity',
  focusDistribution: 'focusDistribution',
  squadAverage: 'squadAverage',
  ageGroupRange: 'ageGroupRange',
  loadStatus: 'loadStatus',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.DevelopmentBlockScalarFieldEnum = {
  id: 'id',
  seasonPlanId: 'seasonPlanId',
  name: 'name',
  startDate: 'startDate',
  endDate: 'endDate',
  focusArea: 'focusArea',
  targetMetrics: 'targetMetrics',
  suggestedLoadRange: 'suggestedLoadRange',
  sessionFocusDistribution: 'sessionFocusDistribution',
  description: 'description',
  createdByUserId: 'createdByUserId',
  createdByRole: 'createdByRole',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TrialEventScalarFieldEnum = {
  id: 'id',
  title: 'title',
  centerId: 'centerId',
  startDateTime: 'startDateTime',
  endDateTime: 'endDateTime',
  ageGroups: 'ageGroups',
  positionsNeeded: 'positionsNeeded',
  format: 'format',
  status: 'status',
  notes: 'notes',
  createdByUserId: 'createdByUserId',
  createdByRole: 'createdByRole',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TrialEventStaffScalarFieldEnum = {
  id: 'id',
  trialEventId: 'trialEventId',
  coachId: 'coachId',
  role: 'role',
  createdAt: 'createdAt'
};

exports.Prisma.TrialistScalarFieldEnum = {
  id: 'id',
  fullName: 'fullName',
  phone: 'phone',
  guardianPhone: 'guardianPhone',
  email: 'email',
  dateOfBirth: 'dateOfBirth',
  preferredFoot: 'preferredFoot',
  primaryPosition: 'primaryPosition',
  secondaryPositions: 'secondaryPositions',
  currentClub: 'currentClub',
  location: 'location',
  height: 'height',
  weight: 'weight',
  injuryNotes: 'injuryNotes',
  consentAccepted: 'consentAccepted',
  consentAcceptedAt: 'consentAcceptedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TrialEventTrialistScalarFieldEnum = {
  id: 'id',
  trialEventId: 'trialEventId',
  trialistId: 'trialistId',
  registeredAt: 'registeredAt',
  notes: 'notes'
};

exports.Prisma.TrialMetricTemplateScalarFieldEnum = {
  id: 'id',
  name: 'name',
  positionScope: 'positionScope',
  specificPositions: 'specificPositions',
  ageScope: 'ageScope',
  description: 'description',
  isDefault: 'isDefault',
  createdByCoachId: 'createdByCoachId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TrialMetricTemplateItemScalarFieldEnum = {
  id: 'id',
  templateId: 'templateId',
  metricKey: 'metricKey',
  displayName: 'displayName',
  category: 'category',
  description: 'description',
  anchors: 'anchors',
  weight: 'weight',
  required: 'required',
  displayOrder: 'displayOrder',
  createdAt: 'createdAt'
};

exports.Prisma.TrialReportScalarFieldEnum = {
  id: 'id',
  trialEventId: 'trialEventId',
  trialistId: 'trialistId',
  templateId: 'templateId',
  createdByCoachId: 'createdByCoachId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  observedPosition: 'observedPosition',
  ageGroup: 'ageGroup',
  observationType: 'observationType',
  confidence: 'confidence',
  minutesObserved: 'minutesObserved',
  weatherNotes: 'weatherNotes',
  pitchNotes: 'pitchNotes',
  strengths: 'strengths',
  risks: 'risks',
  coachSummary: 'coachSummary',
  recommendedAction: 'recommendedAction',
  decisionNotes: 'decisionNotes',
  overallScore: 'overallScore'
};

exports.Prisma.TrialReportValueScalarFieldEnum = {
  id: 'id',
  reportId: 'reportId',
  templateItemId: 'templateItemId',
  value: 'value',
  comment: 'comment',
  confidence: 'confidence',
  createdAt: 'createdAt'
};

exports.Prisma.TrialReportPositionalScalarFieldEnum = {
  id: 'id',
  reportId: 'reportId',
  position: 'position',
  suitability: 'suitability',
  comment: 'comment',
  createdAt: 'createdAt'
};

exports.Prisma.TrialReportRevisionScalarFieldEnum = {
  id: 'id',
  reportId: 'reportId',
  previousData: 'previousData',
  revisedByCoachId: 'revisedByCoachId',
  revisedAt: 'revisedAt',
  reason: 'reason'
};

exports.Prisma.TrialShortlistScalarFieldEnum = {
  id: 'id',
  trialEventId: 'trialEventId',
  name: 'name',
  description: 'description',
  createdByCoachId: 'createdByCoachId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TrialShortlistItemScalarFieldEnum = {
  id: 'id',
  shortlistId: 'shortlistId',
  trialistId: 'trialistId',
  notes: 'notes',
  addedAt: 'addedAt'
};

exports.Prisma.TrialDecisionLogScalarFieldEnum = {
  id: 'id',
  trialEventId: 'trialEventId',
  trialistId: 'trialistId',
  decision: 'decision',
  notes: 'notes',
  decidedByCoachId: 'decidedByCoachId',
  decidedAt: 'decidedAt'
};

exports.Prisma.FooterConfigScalarFieldEnum = {
  id: 'id',
  sectionTitle: 'sectionTitle',
  displayOrder: 'displayOrder',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.FooterLinkScalarFieldEnum = {
  id: 'id',
  footerConfigId: 'footerConfigId',
  label: 'label',
  url: 'url',
  displayOrder: 'displayOrder',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.JsonNullValueInput = {
  JsonNull: Prisma.JsonNull
};

exports.Prisma.NullableJsonNullValueInput = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};
exports.Role = exports.$Enums.Role = {
  ADMIN: 'ADMIN',
  COACH: 'COACH',
  STUDENT: 'STUDENT',
  FAN: 'FAN'
};

exports.StudentStatus = exports.$Enums.StudentStatus = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  TRIAL: 'TRIAL'
};

exports.FanAccountStatus = exports.$Enums.FanAccountStatus = {
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED'
};

exports.FanCenterPreference = exports.$Enums.FanCenterPreference = {
  THREELOK: 'THREELOK',
  DEPOT18: 'DEPOT18',
  BLITZZ: 'BLITZZ',
  TRONIC: 'TRONIC'
};

exports.RewardCampaignType = exports.$Enums.RewardCampaignType = {
  STATIC: 'STATIC',
  DYNAMIC_ROLLING: 'DYNAMIC_ROLLING'
};

exports.CouponCodeType = exports.$Enums.CouponCodeType = {
  SINGLE_USE: 'SINGLE_USE',
  MULTI_USE: 'MULTI_USE'
};

exports.CouponDiscountType = exports.$Enums.CouponDiscountType = {
  PERCENT: 'PERCENT',
  FLAT: 'FLAT',
  FREEBIE: 'FREEBIE'
};

exports.CouponRedemptionStatus = exports.$Enums.CouponRedemptionStatus = {
  REDEEMED: 'REDEEMED',
  REVOKED: 'REVOKED'
};

exports.FanGameType = exports.$Enums.FanGameType = {
  QUIZ: 'QUIZ',
  PREDICT_SCORE: 'PREDICT_SCORE',
  SPIN: 'SPIN',
  COLLECT: 'COLLECT',
  STREAK: 'STREAK'
};

exports.FanProgramInterest = exports.$Enums.FanProgramInterest = {
  EPP: 'EPP',
  SCP: 'SCP',
  WPP: 'WPP',
  FYDP: 'FYDP'
};

exports.FanConversionLeadStatus = exports.$Enums.FanConversionLeadStatus = {
  NEW: 'NEW',
  CONTACTED: 'CONTACTED',
  CONVERTED: 'CONVERTED',
  DROPPED: 'DROPPED'
};

exports.FanPersonaType = exports.$Enums.FanPersonaType = {
  PURE_FAN: 'PURE_FAN',
  ASPIRING_PLAYER: 'ASPIRING_PLAYER',
  ANALYST: 'ANALYST',
  COMMUNITY_SUPPORTER: 'COMMUNITY_SUPPORTER'
};

exports.AttendanceStatus = exports.$Enums.AttendanceStatus = {
  PRESENT: 'PRESENT',
  ABSENT: 'ABSENT',
  EXCUSED: 'EXCUSED'
};

exports.FixtureStatus = exports.$Enums.FixtureStatus = {
  UPCOMING: 'UPCOMING',
  ONGOING: 'ONGOING',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  POSTPONED: 'POSTPONED'
};

exports.MatchSelectionStatus = exports.$Enums.MatchSelectionStatus = {
  SELECTED: 'SELECTED',
  NOT_SELECTED: 'NOT_SELECTED',
  INJURED_UNAVAILABLE: 'INJURED_UNAVAILABLE',
  RESERVE: 'RESERVE'
};

exports.MatchSelectionReason = exports.$Enums.MatchSelectionReason = {
  PERFORMANCE_BASED: 'PERFORMANCE_BASED',
  TACTICAL_FIT: 'TACTICAL_FIT',
  ATTENDANCE_REQUIREMENT: 'ATTENDANCE_REQUIREMENT',
  PHYSICAL_READINESS: 'PHYSICAL_READINESS',
  SQUAD_ROTATION: 'SQUAD_ROTATION',
  INJURY_RECOVERY: 'INJURY_RECOVERY',
  OTHER: 'OTHER'
};

exports.ClubEventType = exports.$Enums.ClubEventType = {
  MATCH: 'MATCH',
  TRAINING: 'TRAINING',
  TRIAL: 'TRIAL',
  SEMINAR: 'SEMINAR',
  MEETING: 'MEETING',
  OTHER: 'OTHER'
};

exports.HomeAway = exports.$Enums.HomeAway = {
  HOME: 'HOME',
  AWAY: 'AWAY'
};

exports.ClubEventStatus = exports.$Enums.ClubEventStatus = {
  SCHEDULED: 'SCHEDULED',
  CONFIRMED: 'CONFIRMED',
  POSTPONED: 'POSTPONED',
  CANCELLED: 'CANCELLED',
  COMPLETED: 'COMPLETED'
};

exports.VideoPlatform = exports.$Enums.VideoPlatform = {
  YOUTUBE: 'YOUTUBE',
  INSTAGRAM: 'INSTAGRAM',
  UPLOADED: 'UPLOADED'
};

exports.DrillMediaType = exports.$Enums.DrillMediaType = {
  LINK: 'LINK',
  IMAGE: 'IMAGE',
  PDF: 'PDF',
  DOCUMENT: 'DOCUMENT',
  VIDEO: 'VIDEO'
};

exports.PostMediaType = exports.$Enums.PostMediaType = {
  IMAGE: 'IMAGE',
  VIDEO: 'VIDEO',
  LINK: 'LINK'
};

exports.PostPlatform = exports.$Enums.PostPlatform = {
  YOUTUBE: 'YOUTUBE',
  INSTAGRAM: 'INSTAGRAM',
  INTERNAL: 'INTERNAL'
};

exports.PostApprovalStatus = exports.$Enums.PostApprovalStatus = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED'
};

exports.BadgeType = exports.$Enums.BadgeType = {
  FIRST_VOTE: 'FIRST_VOTE',
  TOP_WEEKLY: 'TOP_WEEKLY',
  TOP_MONTHLY: 'TOP_MONTHLY',
  STREAK_5: 'STREAK_5',
  STREAK_10: 'STREAK_10',
  STREAK_20: 'STREAK_20',
  CENTURY: 'CENTURY',
  FIVE_HUNDRED: 'FIVE_HUNDRED',
  THOUSAND: 'THOUSAND',
  COACH_FAVORITE: 'COACH_FAVORITE',
  PEER_FAVORITE: 'PEER_FAVORITE',
  CONSISTENT: 'CONSISTENT'
};

exports.LeadStatus = exports.$Enums.LeadStatus = {
  NEW: 'NEW',
  CONTACTED: 'CONTACTED',
  CONVERTED: 'CONVERTED',
  LOST: 'LOST',
  QUALIFIED: 'QUALIFIED',
  CONTACT_REQUESTED: 'CONTACT_REQUESTED'
};

exports.CrmUserRole = exports.$Enums.CrmUserRole = {
  AGENT: 'AGENT'
};

exports.CrmUserStatus = exports.$Enums.CrmUserStatus = {
  ACTIVE: 'ACTIVE',
  DISABLED: 'DISABLED'
};

exports.CrmLeadSourceType = exports.$Enums.CrmLeadSourceType = {
  WEBSITE: 'WEBSITE',
  LEGACY: 'LEGACY',
  CHECKOUT: 'CHECKOUT',
  FAN: 'FAN',
  MANUAL: 'MANUAL'
};

exports.CrmLeadStage = exports.$Enums.CrmLeadStage = {
  NEW: 'NEW',
  CONTACTED: 'CONTACTED',
  FOLLOW_UP: 'FOLLOW_UP',
  WILL_JOIN: 'WILL_JOIN',
  JOINED: 'JOINED',
  UNINTERESTED_NO_RESPONSE: 'UNINTERESTED_NO_RESPONSE'
};

exports.CrmLeadStatus = exports.$Enums.CrmLeadStatus = {
  OPEN: 'OPEN',
  CLOSED: 'CLOSED'
};

exports.CrmActivityType = exports.$Enums.CrmActivityType = {
  NOTE: 'NOTE',
  CALL: 'CALL',
  EMAIL: 'EMAIL',
  WHATSAPP: 'WHATSAPP',
  MEETING: 'MEETING',
  STAGE_CHANGED: 'STAGE_CHANGED',
  STATUS_CHANGED: 'STATUS_CHANGED',
  OWNER_CHANGED: 'OWNER_CHANGED',
  IMPORTED: 'IMPORTED',
  MERGED: 'MERGED'
};

exports.CrmTaskStatus = exports.$Enums.CrmTaskStatus = {
  OPEN: 'OPEN',
  DONE: 'DONE',
  CANCELLED: 'CANCELLED'
};

exports.CrmImportStatus = exports.$Enums.CrmImportStatus = {
  DRAFT: 'DRAFT',
  VALIDATED: 'VALIDATED',
  COMMITTED: 'COMMITTED',
  FAILED: 'FAILED'
};

exports.SystemActorType = exports.$Enums.SystemActorType = {
  ADMIN: 'ADMIN',
  COACH: 'COACH',
  STUDENT: 'STUDENT',
  FAN: 'FAN',
  CRM: 'CRM',
  SYSTEM: 'SYSTEM'
};

exports.OrderStatus = exports.$Enums.OrderStatus = {
  PENDING_PAYMENT: 'PENDING_PAYMENT',
  PAID: 'PAID',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
  SHIPPED: 'SHIPPED',
  DELIVERED: 'DELIVERED'
};

exports.TimelineEventType = exports.$Enums.TimelineEventType = {
  JOINED_ACADEMY: 'JOINED_ACADEMY',
  ATTENDANCE_MILESTONE: 'ATTENDANCE_MILESTONE',
  LEAGUE_PARTICIPATION: 'LEAGUE_PARTICIPATION',
  MATCH_APPEARANCE: 'MATCH_APPEARANCE',
  PERFORMANCE_EVALUATION: 'PERFORMANCE_EVALUATION',
  PROMOTION: 'PROMOTION',
  COACH_FEEDBACK: 'COACH_FEEDBACK',
  BADGE_EARNED: 'BADGE_EARNED',
  PAYMENT_MILESTONE: 'PAYMENT_MILESTONE',
  CUSTOM: 'CUSTOM'
};

exports.EnergyLevel = exports.$Enums.EnergyLevel = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH'
};

exports.MetricCategory = exports.$Enums.MetricCategory = {
  TECHNICAL: 'TECHNICAL',
  PHYSICAL: 'PHYSICAL',
  MENTAL: 'MENTAL',
  ATTITUDE: 'ATTITUDE',
  GOALKEEPING: 'GOALKEEPING'
};

exports.MetricSourceContext = exports.$Enums.MetricSourceContext = {
  TRAINING_BLOCK: 'TRAINING_BLOCK',
  MATCH_BLOCK: 'MATCH_BLOCK',
  TRIAL: 'TRIAL',
  MONTHLY_REVIEW: 'MONTHLY_REVIEW',
  QUARTERLY_ASSESSMENT: 'QUARTERLY_ASSESSMENT',
  SEASON_START: 'SEASON_START',
  SEASON_END: 'SEASON_END',
  CUSTOM: 'CUSTOM'
};

exports.PlayerPosition = exports.$Enums.PlayerPosition = {
  GK: 'GK',
  CB: 'CB',
  FB: 'FB',
  WB: 'WB',
  DM: 'DM',
  CM: 'CM',
  AM: 'AM',
  W: 'W',
  ST: 'ST'
};

exports.ScoutingBoardType = exports.$Enums.ScoutingBoardType = {
  CENTRE_VIEW: 'CENTRE_VIEW',
  CLUB_WIDE: 'CLUB_WIDE',
  CUSTOM: 'CUSTOM'
};

exports.ScoutingDecisionState = exports.$Enums.ScoutingDecisionState = {
  OBSERVING: 'OBSERVING',
  TRIAL_RECOMMENDED: 'TRIAL_RECOMMENDED',
  READY_FOR_PROMOTION: 'READY_FOR_PROMOTION',
  HOLD_FOR_DEVELOPMENT: 'HOLD_FOR_DEVELOPMENT',
  INTERVENTION_NEEDED: 'INTERVENTION_NEEDED'
};

exports.SeasonPhaseType = exports.$Enums.SeasonPhaseType = {
  PREPARATION: 'PREPARATION',
  COMPETITIVE: 'COMPETITIVE',
  RECOVERY: 'RECOVERY',
  TRANSITION: 'TRANSITION'
};

exports.TrainingIntensity = exports.$Enums.TrainingIntensity = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH'
};

exports.TrainingFocus = exports.$Enums.TrainingFocus = {
  TECHNICAL: 'TECHNICAL',
  TACTICAL: 'TACTICAL',
  PHYSICAL: 'PHYSICAL',
  RECOVERY: 'RECOVERY'
};

exports.TrialEventStatus = exports.$Enums.TrialEventStatus = {
  DRAFT: 'DRAFT',
  LIVE: 'LIVE',
  CLOSED: 'CLOSED',
  ARCHIVED: 'ARCHIVED'
};

exports.TrialPositionScope = exports.$Enums.TrialPositionScope = {
  OUTFIELD: 'OUTFIELD',
  GK: 'GK',
  ANY: 'ANY'
};

exports.TrialMetricCategory = exports.$Enums.TrialMetricCategory = {
  TECHNICAL: 'TECHNICAL',
  PHYSICAL: 'PHYSICAL',
  MENTAL: 'MENTAL',
  ATTITUDE: 'ATTITUDE',
  TACTICAL: 'TACTICAL',
  ROLE_FIT: 'ROLE_FIT'
};

exports.TrialObservationType = exports.$Enums.TrialObservationType = {
  DRILLS: 'DRILLS',
  MATCH: 'MATCH',
  BOTH: 'BOTH'
};

exports.TrialRecommendedAction = exports.$Enums.TrialRecommendedAction = {
  INVITE_BACK: 'INVITE_BACK',
  SELECT_NOW: 'SELECT_NOW',
  DEVELOPMENT_POOL: 'DEVELOPMENT_POOL',
  NOT_SELECTED: 'NOT_SELECTED',
  NEED_MORE_DATA: 'NEED_MORE_DATA'
};

exports.Prisma.ModelName = {
  Center: 'Center',
  Coach: 'Coach',
  CoachCenter: 'CoachCenter',
  Student: 'Student',
  Payment: 'Payment',
  FanUser: 'FanUser',
  FanProfile: 'FanProfile',
  FanTier: 'FanTier',
  FanSponsor: 'FanSponsor',
  RewardCampaign: 'RewardCampaign',
  CouponPool: 'CouponPool',
  CouponCode: 'CouponCode',
  CouponRedemption: 'CouponRedemption',
  FanQuest: 'FanQuest',
  FanGameSession: 'FanGameSession',
  FanConversionLead: 'FanConversionLead',
  FanOnboarding: 'FanOnboarding',
  FanPointLedger: 'FanPointLedger',
  FanBadgeEarned: 'FanBadgeEarned',
  MatchdayMoment: 'MatchdayMoment',
  DynamicRewardRule: 'DynamicRewardRule',
  AuditLog: 'AuditLog',
  Session: 'Session',
  SessionParticipant: 'SessionParticipant',
  Attendance: 'Attendance',
  Fixture: 'Fixture',
  FixturePlayer: 'FixturePlayer',
  ClubEvent: 'ClubEvent',
  ClubEventPlayer: 'ClubEventPlayer',
  Video: 'Video',
  Post: 'Post',
  Comment: 'Comment',
  Vote: 'Vote',
  StudentStats: 'StudentStats',
  Badge: 'Badge',
  WebsiteLead: 'WebsiteLead',
  LegacyLead: 'LegacyLead',
  CrmUser: 'CrmUser',
  CrmSettings: 'CrmSettings',
  CrmLead: 'CrmLead',
  CrmManualLeadSource: 'CrmManualLeadSource',
  CrmActivity: 'CrmActivity',
  CrmTask: 'CrmTask',
  CrmImportJob: 'CrmImportJob',
  CrmImportRow: 'CrmImportRow',
  SystemActivityLog: 'SystemActivityLog',
  Product: 'Product',
  Order: 'Order',
  OrderItem: 'OrderItem',
  CheckoutLead: 'CheckoutLead',
  TimelineEvent: 'TimelineEvent',
  MonthlyFeedback: 'MonthlyFeedback',
  WellnessCheck: 'WellnessCheck',
  ProgressRoadmap: 'ProgressRoadmap',
  CentreMonthlyMetrics: 'CentreMonthlyMetrics',
  PlayerMetricDefinition: 'PlayerMetricDefinition',
  PlayerMetricSnapshot: 'PlayerMetricSnapshot',
  PlayerMetricValue: 'PlayerMetricValue',
  PlayerPositionalSuitability: 'PlayerPositionalSuitability',
  PlayerTraitSnapshot: 'PlayerTraitSnapshot',
  PlayerMetricAuditLog: 'PlayerMetricAuditLog',
  PlayerCoachNote: 'PlayerCoachNote',
  PlayerReadinessIndex: 'PlayerReadinessIndex',
  ScoutingBoard: 'ScoutingBoard',
  ScoutingBoardPlayer: 'ScoutingBoardPlayer',
  ScoutingDecisionLog: 'ScoutingDecisionLog',
  ParentDevelopmentReport: 'ParentDevelopmentReport',
  SeasonPlan: 'SeasonPlan',
  SeasonPhase: 'SeasonPhase',
  TrainingSessionLoad: 'TrainingSessionLoad',
  PlayerWeeklyLoad: 'PlayerWeeklyLoad',
  DevelopmentBlock: 'DevelopmentBlock',
  TrialEvent: 'TrialEvent',
  TrialEventStaff: 'TrialEventStaff',
  Trialist: 'Trialist',
  TrialEventTrialist: 'TrialEventTrialist',
  TrialMetricTemplate: 'TrialMetricTemplate',
  TrialMetricTemplateItem: 'TrialMetricTemplateItem',
  TrialReport: 'TrialReport',
  TrialReportValue: 'TrialReportValue',
  TrialReportPositional: 'TrialReportPositional',
  TrialReportRevision: 'TrialReportRevision',
  TrialShortlist: 'TrialShortlist',
  TrialShortlistItem: 'TrialShortlistItem',
  TrialDecisionLog: 'TrialDecisionLog',
  FooterConfig: 'FooterConfig',
  FooterLink: 'FooterLink'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
